import './globals.css';
import Navbar from '@/components/navbar/Navbar';
import ThemeWrapper from './ThemeWrapper';

export const metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ThemeWrapper>
          <Navbar />
          <main>{children}</main>
        </ThemeWrapper>
      </body>
    </html>
  );
}
